### ISSUE TITLE
查看处于有期徒刑的成员 保释

### ISSUE THREAD

**Issue by stjak123** [zly2006/yet-another-qq-bot#10]
加入 #小黑屋 命令查看处于有期徒刑的成员的列表
if (message.content.startsWith("#小黑屋")) {
    val membersOnProbation = group.members.filter { member ->
        member.banUntil > System.currentTimeMillis()
    }
    val memberNames = membersOnProbation.joinToString(", ") { it.name }
    if (membersOnProbation.isNotEmpty()) {
        group.sendMessage("以下成员处于有期徒刑状态： $memberNames")
    } else {
        group.sendMessage("当前没有成员处于有期徒刑状态。")
    }
}
加入 #保释 @某人 以保释成员 所需金币=剩余时间(秒)*5
if (message.content.startsWith("#保释")) {
    val target = resolveTarget(message, bot)?.let { profile(it) } ?: run {
        group.sendMessage("无法找到该成员")
        return@subscribeAlways
    }
    if (target.banUntil <= System.currentTimeMillis()) {
        group.sendMessage("该成员目前没有被关进小黑屋")
        return@subscribeAlways
    }
    val remainingTime = (target.banUntil - System.currentTimeMillis()) / 1000 
    val bailAmount = remainingTime * 5
    if (target.money < bailAmount) {
        group.sendMessage("该成员金币不足以支付保释金")
        return@subscribeAlways
    }
    target.money -= bailAmount
    target.banUntil = System.currentTimeMillis()
    group.sendMessage("${target.at()} 已成功保释出狱，保释金为 $bailAmount 金币。")
}

这只是一个提议 所提供的代码仅供参考

**Comment by zly2006** [comment]
导致封禁的原因目前只有小号和偷金币

偷金币会导致7200秒的封禁，平均收益75元/次，希望你提供更多信息以便我可以确认5金币/秒合理

**Comment by stjak123** [comment]
确实 合理的价格应当为0.015金币/秒 这样7200秒解禁需要花费108金币

**Comment by zly2006** [comment]
0.02吧

**Comment by stjak123** [comment]
行呀 决定权在你(•́⌄•́๑)✧

**Comment by stjak123** [comment]
reopen
