### ISSUE TITLE
偷金币

### ISSUE THREAD

**Issue by Normal-pcer** [zly2006/yet-another-qq-bot#2]
**详细介绍此功能**
结合已有的金币组件，添加偷金币功能。
一人一天可以执行一次#偷金币:<QQ号>命令，偷得5-40金币。若被偷金币的玩家在2小时内发现，可以执行#举报小偷:<QQ号>指令，拿回全部被偷金币，并额外增加20%作为奖励。被举报的玩家会被罚款盗窃数目的50%且两天内不能签到。

**你希望此功能如何被实现？**
一个你最推荐的实现方案，如果你正在或打算实现此功能请再次说明。

**有其他的相关建议吗？**
其他可选的实现方案，如果是其他的建议开启另一个issue。

**Additional context**

**Comment by zly2006** [comment]
关于期望收益的计算：

设 $P=偷金币被发现$ ，$E_{获得}=(1- P) \times 22.5 - P \times 211.25 $ 解得 $P=11.92%$ 时，偷金币会亏

请给出此概率合乎平衡性的论证


> 2023年4月27日 22:55，普通的pc君 ***@***.***> 写道：
> 
> 
> 一个你最推荐的实现方案，如果你正在或打算实现此功能请再次说明。
> 
> 有其他的相关建议吗？
> 其他可选的实现方案，如果是其他的建议开启另一个issue。
> 
> Additional context
>

**Comment by Normal-pcer** [comment]
你不知道对方会不会查看自己的金币是否会被偷（bushi

**Comment by Normal-pcer** [comment]
这些数据只是一个示例，并不保证平衡，可以自行修改

**Comment by Normal-pcer** [comment]
此外，为避免不上线的人被偷，可以添加#冻结账户，此时金币数不能被修改。
#冻结账户和#解冻账户均为一周可以执行一次。

**Comment by zly2006** [comment]
不建议的功能，建议设计为偷金币冷却为一天等设定。

此外，您应该对概率设定做出更详细的规划，这是使您的功能能得以被实现的关键。

**Comment by Normal-pcer** [comment]
以下为示例方案：
平均值为75金币，具体区间为10-150
可以被发现的时间为48小时
被发现的额外罚款为20%
举报小偷的奖励是15%
偷金币的冷却是1天
同时，尽管概率较小，小偷也会有“一夜暴富”的机会。

我认为冻结账户是必要的，比如有人由于学业没有时间看群，一个学期会被偷走不知道多少金币。此时他也无法获得金币，相当于“与世隔绝”。

//数学部分已删除

**Comment by Miraculy** [comment]
臣附议

**Comment by zly2006** [comment]
感谢你提供的建议。
小偷期望为$ ( -0.2 * p + 1 * (1-p) )*80 $ p=83% 时E=0
被偷者期望收益为$ ( 0.15 * p - 1 * (1-p) )*80 $ p=86% 时E=0
似乎你的计算有点问题，但是数值还挺合理的

**Comment by Normal-pcer** [comment]
我稍后会提一个pr

**Comment by Normal-pcer** [comment]
#7
